### ISSUE TITLE
Bad ordering of interpolated cross-section uncertainties?

### ISSUE THREAD

**Issue by jshahinian** [APN-Pucky/HEPi#281]
Hi,

Thanks for putting together the `HEPi-fast` tool, it's super convenient! But I think I noticed a mismatch between the order of the outputs described in the README and what the tool actually spits out. The README says the ordering is like this:

```
id | Central value | error down | error up | error pdf down | error pdf up | error scale down | error scale up
```
while I think the scale uncertainties are actually reported before the pdf uncertainties, i.e.
```
id | Central value | error down | error up | error scale down | error scale up | error pdf down | error pdf up
```
At least that's what I glean from both the size of the uncertainties that are reported (pdf uncertainties should generally be larger than the scale uncertainties) and from the relevant [print statement](https://github.com/APN-Pucky/HEPi/blob/master/hepi/fast.py#L269).

Should the order on the README be updated? As a side note, would it make sense to use the same ordering that is listed on the official [SUSY XSection twikis](https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SUSYCrossSections13x6TeVn2x1wino), e.g. something like this?
```
id | Central value | error down | error up | error scale up | error pdf up | error scale down | error pdf down
```

**Comment by jshahinian** [comment]
In slightly worse news, we've also realized that the up/down variations reported by the tool are also swapped with respect to the values on the twiki. Here's an example for Wino-like N2C1p production with a mass of 200 GeV:
```
$ hepi-fast 13600_wino_1000023_1000024_NNLL.json
> 200
0 200.0 1.2992818 -0.05042042126595758 0.05116085317111718 -0.012700500000000003 0.015379099999999868 -0.04879463270060147 0.04879463270060147
```
Now let's assume that the reported pdf and scale uncertainties are indeed swapped, as described above. Then I identify:

- Scale uncertainty down = -0.012700500000000003 pb --> roughly -1.0%
- Scale uncertainty up = 0.015379099999999868 pb --> roughly +1.2%

The corresponding [twiki](https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SUSYCrossSections13x6TeVn2x1wino) contains this point, but reports the opposite:
- Scale uncertainty down = -1.2%
- Scale uncertainty up = +1.0%

So there's a mismatch somewhere, but I'm not sure if it's coming from the interpolation tool or a mistake when these values were added to the twiki.

**Comment by APN-Pucky** [comment]
Quick note without having checked everything in detail (more will follow soon):
https://arxiv.org/pdf/2304.11915 Table 6, second half at 200 says scale up is -1.2% and up 1.0% as in the twiki.
Just for clarity the data is first produced in the paper (with resummino+hepi), then exported in to the json https://github.com/APN-Pucky/HEPi/blob/d44cc2ec64f53570a0c09afcd0d481829136748f/hepi/data/json/13600_wino_1000023_1000024_NNLL.json#L32 there the values are also still correct, then I uploaded to twiki. So the accidental mixture happens in the latest stage namely hepi-fast.

I think the readme/hepi-fast columns are swapped because I initially thought of using the same as n(n)ll-fast. To be fixed!

**Comment by APN-Pucky** [comment]
I am not too much of a fan of the twiki ordering. I just kept it there as it was done there before.
The fix I am going to merge will then order it as
```
ID | Central value | error up | error down | error scale up | error scale down | error pdf up | error pdf down
```
seems to align best with [nnll-fast](https://www.uni-muenster.de/Physik.TP/~akule_01/nnllfast/doku.php?id=start) and as one would naturally give first the upper error and then the lower.

**Comment by APN-Pucky** [comment]
Thank you for noticing and informing me about this issue! I have only used hepi-fast for the central values and quick plotting.

**Comment by jshahinian** [comment]
Thanks a ton for the quick fix and clear explanation, @APN-Pucky!
It's totally fine that the ordering doesn't agree with the twiki (I'm not too fond of the twiki ordering either...), I trust users can handle that mapping themselves if they're ever doing these sorts of comparisons.
